export const initialState = [{
    'id': 1,
    'text': 'Tabbitha',
    'selected': true
  }, {
    'id': 2,
    'text': 'Rickie',
    'selected': false
  }, {
    'id': 3,
    'text': 'Jacquelin',
    'selected': false
  }, {
    'id': 4,
    'text': 'Dorri',
    'selected': false
  }, {
    'id': 5,
    'text': 'Brigham',
    'selected': false
  }, {
    'id': 6,
    'text': 'Ajinkya',
    'selected': false
  }, {
    'id': 7,
    'text': 'Hadley',
    'selected': false
  }, {
    'id': 8,
    'text': 'Orland',
    'selected': false
  }, {
    'id': 9,
    'text': 'Fifine',
    'selected': false
  }, {
    'id': 10,
    'text': 'Trudie',
    'selected': false
  }, {
    'id': 11,
    'text': 'Henderson',
    'selected': false
  }, {
    'id': 12,
    'text': 'Korrie',
    'selected': false
  }, {
    'id': 13,
    'text': 'Letti',
    'selected': false
  }, {
    'id': 14,
    'text': 'Carny',
    'selected': false
  }, {
    'id': 15,
    'text': 'Sol',
    'selected': false
  }, {
    'id': 16,
    'text': 'Zaria',
    'selected': false
  }, {
    'id': 17,
    'text': 'Flss',
    'selected': false
  }, {
    'id': 18,
    'text': 'Preston',
    'selected': false
  }, {
    'id': 19,
    'text': 'Norman',
    'selected': false
  }, {
    'id': 20,
    'text': 'Jermain',
    'selected': false
}]